### PR TITLE
Allow specifying custom createSecureContext for sniCallback

### LINKED ISSUE #39: Usage in cluster mode?
Hello, I'm the author of http-master (https://github.com/virtkick/http-master) and would like to use your module to implement letsencrypt support. The architecture I have is one central process and multiple workers. Certificates from disk are managed by the master process and serialized to individual workers.

With letsencrypt-express I imagine that the master process would need to have the letsencrypt state and actually issue the renewal requests, whereas the workers would have to ask the master process for certificates data. Can your module accomodate such use case?

### PR DESCRIPTION
**Pull request by Rush**
This allows for example to serialize the result of sniCallback
from a master process to a worker process if the module is used
in a cluster configuration.

Fixes #39

### CODE REVIEW

**Comment by Rush** [comment]
@coolaj86 ping

**Comment by coolaj86** [comment]
Sorry for the late reply. I made you a contributor to the project. Feel free to merge, test, and let me know when to pull and republish.

Thanks!

**Comment by Rush** [comment]
@coolaj86 did you? It seems I don't have rights to merge this branch.

**Comment by coolaj86** [comment]
FYI: All of the SNICallback stuff is now managed in the sni plugin. The default is https://github.com/Daplie/le-sni-auto.

**Pull request closed without merging**
